# Generated by Django 6.0.1 on 2026-02-15 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the project used in URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the project", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uk", "Українська"),
                            ("en", "English"),
                            ("pl", "Polski"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                            ("nl", "Nederlands"),
                            ("cs", "Čeština"),
                            ("sk", "Slovenčina"),
                            ("ro", "Română"),
                            ("hu", "Magyar"),
                            ("bg", "Български"),
                            ("el", "Ελληνικά"),
                            ("sv", "Svenska"),
                            ("da", "Dansk"),
                            ("no", "Norsk"),
                            ("fi", "Suomi"),
                            ("ru", "Русский"),
                            ("be", "Беларуская"),
                            ("hr", "Hrvatski"),
                            ("sr", "Српски"),
                            ("sl", "Slovenščina"),
                            ("zh-CN", "简体中文"),
                            ("zh-TW", "繁體中文"),
                            ("ja", "日本語"),
                            ("ko", "한국어"),
                            ("vi", "Tiếng Việt"),
                            ("th", "ไทย"),
                            ("hi", "हिन्दी"),
                            ("ar", "العربية"),
                            ("he", "עברית"),
                            ("tr", "Türkçe"),
                            ("id", "Bahasa Indonesia"),
                            ("ms", "Bahasa Melayu"),
                            ("fa", "فارسی"),
                            ("bn", "বাংলা"),
                            ("ur", "اردو"),
                            ("sw", "Kiswahili"),
                        ],
                        help_text="Target language (ISO 639-1)",
                        max_length=5,
                    ),
                ),
                (
                    "is_base_language",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this language is the base language of the project",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this language belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Language",
                "verbose_name_plural": "Project Languages",
                "ordering": ["project__name", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "language"), name="unique_project_language"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_base_language", True)),
                        fields=("project",),
                        name="unique_base_language_per_project",
                    ),
                ],
            },
        ),
    ]
