# Generated by Django 6.0.1 on 2026-01-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the translation",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the translation key",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Unique identifier for the translation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_keys",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Key",
                "verbose_name_plural": "Translation Keys",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TranslationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(help_text="Translated text")),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language of the translation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_values",
                        to="languages.language",
                    ),
                ),
                (
                    "translation_key",
                    models.ForeignKey(
                        help_text="The translation key this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="translations.translationkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Value",
                "verbose_name_plural": "Translation Values",
                "ordering": ["translation_key", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("translation_key", "language"),
                        name="unique_translation_per_language",
                    )
                ],
            },
        ),
    ]
