# Generated by Django 6.0.1 on 2026-02-15 22:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the translation",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Use lowercase letters separated by a single "_" (e.g., my_code_name).',
                                regex="^[a-z]+(_[a-z]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the translation key",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this translation key belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_keys",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Key",
                "verbose_name_plural": "Translation Keys",
                "ordering": ["project__slug", "key"],
            },
        ),
        migrations.CreateModel(
            name="TranslationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uk", "Українська"),
                            ("en", "English"),
                            ("pl", "Polski"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                            ("nl", "Nederlands"),
                            ("cs", "Čeština"),
                            ("sk", "Slovenčina"),
                            ("ro", "Română"),
                            ("hu", "Magyar"),
                            ("bg", "Български"),
                            ("el", "Ελληνικά"),
                            ("sv", "Svenska"),
                            ("da", "Dansk"),
                            ("no", "Norsk"),
                            ("fi", "Suomi"),
                            ("ru", "Русский"),
                            ("be", "Беларуская"),
                            ("hr", "Hrvatski"),
                            ("sr", "Српски"),
                            ("sl", "Slovenščina"),
                            ("zh-CN", "简体中文"),
                            ("zh-TW", "繁體中文"),
                            ("ja", "日本語"),
                            ("ko", "한국어"),
                            ("vi", "Tiếng Việt"),
                            ("th", "ไทย"),
                            ("hi", "हिन्दी"),
                            ("ar", "العربية"),
                            ("he", "עברית"),
                            ("tr", "Türkçe"),
                            ("id", "Bahasa Indonesia"),
                            ("ms", "Bahasa Melayu"),
                            ("fa", "فارسی"),
                            ("bn", "বাংলা"),
                            ("ur", "اردو"),
                            ("sw", "Kiswahili"),
                        ],
                        help_text="Language of the translation (ISO 639-1)",
                        max_length=5,
                    ),
                ),
                ("value", models.TextField(help_text="Translated text")),
                (
                    "translation_key",
                    models.ForeignKey(
                        help_text="The translation key this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="translations.translationkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Value",
                "verbose_name_plural": "Translation Values",
                "ordering": ["translation_key__key", "language"],
            },
        ),
        migrations.AddIndex(
            model_name="translationkey",
            index=models.Index(
                fields=["project", "key"], name="translation_project_7b6f8f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="translationkey",
            constraint=models.UniqueConstraint(
                fields=("key", "project"), name="unique_key_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="translationvalue",
            index=models.Index(
                fields=["translation_key", "language"],
                name="translation_transla_aea5ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationvalue",
            constraint=models.UniqueConstraint(
                fields=("translation_key", "language"),
                name="unique_translation_per_language",
            ),
        ),
    ]
