# Generated by Django 6.0.1 on 2026-02-24 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationkey",
            name="key",
            field=models.CharField(
                help_text="Lowercase letters and digits (a-z, 0-9), separated by dot or underscore; e.g. api.v1.endpoint or form.submit_button. At least 2 segments.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Use lowercase letters and digits separated by "_" or "." (e.g., my_code_name, api.v1.endpoint).',
                        regex="^[a-z0-9]+(?:[._][a-z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
